### ISSUE TITLE
Restructure the Using Pipelines assembly

### ISSUE THREAD

**Issue by Preeticp** [openshift/pipelines-docs#105]
The following changes need to be done:
- [x]  The Using Pipelines assembly should be renamed to Creating applications with CI/CD pipelines.
- [x] The first module should be Creating a project instead of Deploying..., delete image attribute, and move step 4 and 5 (first 2 sentences only) to the last module Checking Pipelines...
- [x] Replace Dev console screenshot in Checking Pipelines...to the one in the tutorial. Add a sentence saying for details on using the developer perspective see the dev perspective section with a link.

**Comment by nkakkar81** [comment]
- [x] add more info on service account in first module ->step 3

**Comment by Preeticp** [comment]
Fixed via #110
