### ISSUE TITLE
Broken links on Creating applications with CI/CD Pipelines page

### ISSUE THREAD

**Issue by jeffhoek** [openshift/pipelines-docs#119]
**Describe the Bug**
When going through "Creating applications with CI/CD Pipelines" on the "Procedure" `oc create -f ...` steps it returns a 404 (page not found.)

**Steps to Reproduce**
1. Follow the steps in the "Creating applications with CI/CD Pipelines" guide, up to this step:
```
oc create -f https://raw.githubusercontent.com/openshift/pipelines-tutorial/master/pipeline/update_deployment_task.yaml
```

**Expected Behavior**
The `oc apply -f ...` command should succeed.

**Additional context**
Broken links are here https://github.com/openshift/pipelines-docs/blob/f32949579d6899965959294b3a704da777b62b5c/docs/0.10.5/assembly_creating-applications-with-cicd-pipelines.html#L273-L274

**Comment by Preeticp** [comment]
Deprecated: This documentation repo has been deprecated. Please visit the link below for the latest documentation.
https://docs.openshift.com/container-platform/latest/pipelines/understanding-openshift-pipelines.html
