### ISSUE TITLE
Add steps for publishing the docs using antora

### ISSUE THREAD

**Issue by Preeticp** [openshift/pipelines-docs#31]
We need documentation on publishing the docs using Antora with some links etc. in the Contributing guidelines.
@pmacko1 can you please take this task up? You have already provided steps here:
1. install antora
2. fork openshift repo
3. do changes in master
4. preview with $ antora local-site.yml (previews only current branch) so you won't see the versioning -> output file is in build/site/index.html
5. merge to respective branch if your work is finished
6. checkout to master
7. antora --clean --fetch site.yml
8. copy contents of build/site into docs + overwrite
9. post a pr to openshift and cherry pick to respective branches.
10. output is published from master branch to github.io (edited) 

Instructions from Joan: To publish latest PRs: 1. install active node, 2. Install antora, 3. Run antora local-site.yml, 4. Run cp -r pipelines-docs/build/site/ pipelines-docs/docs/docs/0.7

I am going to test these today and see if they need to be modified. I will add comments in case we do need changes.

**Comment by nebelsprachen** [comment]
Commands to rebuild:

1)` antora --clean --fetch site.yml`       
2) `antora site.yml`
3) `cp -r build/site/docs docs`
4) `git add .`
5) `git commit -m "<message>`
6) `git push origin <branch name>`
