### ISSUE TITLE
create PipelineResource as normal user

### ISSUE THREAD

**Issue by rbaumgar** [openshift/pipelines-docs#66]
**Describe the Bug**
When I create a PipelineResource as a normal user, i receive
pipelineresources.tekton.dev is forbidden: User "demo" cannot create resource "pipelineresources" in API group "tekton.dev" at the cluster scope

**Steps to Reproduce**
1. OpenShift version 4.2 installed
2. OpenShift Pipelines installed with Operator
3. login with user demo
4. use doc until 3.3

**Expected Behavior**
I think it should work as normal user.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by siamaksade** [comment]
cc @vdemeester @sthaha

**Comment by siamaksade** [comment]
@rbaumgar could you provide more details about your cluster and the user you are authenticated as and a more complete log. 

Here is the log of my attempt to run as a non-admin user: https://pastebin.com/raw/nQk9z9Uy

**Comment by rbaumgar** [comment]
Siamak,

you are right plain oc works, but when I open the developer console,
going to search and search for pipelineresouce...
--> pipelineresources.tekton.dev is forbidden: User "demo" cannot list
resource "pipelineresources" in API group "tekton.dev" at the cluster scope
see screen shot

[image: image.png]

**Comment by siamaksade** [comment]
@rbaumgar could you validate it again to see if the issue still exists. It is fixed to my knowledge. Validated on OCP 4.3

**Comment by rbaumgar** [comment]
@siamaksade Validated against OCP 4.3.0 / CRC 1.6.0

**Comment by Preeticp** [comment]
Deprecated: This documentation repo has been deprecated. Please visit the link below for the latest documentation.

https://docs.openshift.com/container-platform/latest/pipelines/understanding-openshift-pipelines.html
