### ISSUE TITLE
Clarify Procedures to Update Content

### ISSUE THREAD

**Issue by adambkaplan** [openshift/pipelines-docs#77]
**Is your feature request related to a problem? Please describe.**
The current contributing guides do not have instructions on how to update content.
Developers who are unfamiliar with the content generation framework have no clue where to find the current content source and make changes.

**Describe the solution you would like to see**
1. A single `CONTRIBUTING.md` file summarizing/linking the existing contributing guides.
2. A separate markdown file describing how the content is organized.
3. A `Makefile` with commands on how to generate the HTML from the asciidoc content.

**Comment by Preeticp** [comment]
Fixed via #98
