### ISSUE TITLE
[v0.7.0] Pipeline content has invalid ARGS param

### ISSUE THREAD

**Issue by adambkaplan** [openshift/pipelines-docs#79]
**Describe the Bug**

There is a mismatch between the example pipeline content in the docs and the version on github. The content in the docs has a single string value for the `ARGS` parameter, whereas the github content in `pipelines-tutorial` has an array.

**Steps to Reproduce**

1. Copy the content in [Assembling a pipeline](https://openshift.github.io/pipelines-docs/docs/docs/0.7/proc_assembling-a-pipeline.html) into a YAML file.
2. Create/apply the pipeline YAML
3. Start a pipeline run as specified in [Triggering and Running a Pipeline](https://openshift.github.io/pipelines-docs/docs/docs/0.7/proc_triggering-and-running-a-pipeline.html)

**Expected Behavior**

Pipeline runs successfully.

**Actual Behavior**

Pipeline fails to run due an invalid value for the `ARGS` parameter.

**Comment by Preeticp** [comment]
@adambkaplan thank you for raising the issue. The content has been updated as per the latest changes in the tutorial, this was true of 0.7 release, the current release 0.10.5 is up to date. I am closing this issue for now, please feel free to reopen it in case you see anything missing. 
Also the contributing doc has been updated with instructions for contributing and publishing docs, we would be happy to receive PRs.
