### ISSUE TITLE
Missing examples of different pipeline resource types

### ISSUE THREAD

**Issue by karthikjeeyar** [openshift/pipelines-docs#8]
There are four types of pipeline resources that we support currently, but the docs contain only the examples of two resources (git and image). It would be helpful for developers if the docs contain all the information about the pipeline resources types.
Each type of resources can have a different set of params eg: type `git` can have `url` and `revision`, similarly, can we add all the types and associated params in this doc?

cc: @siamaksade @Preeticp

**Comment by Preeticp** [comment]
@siamaksade I see information regarding this in the upstream docs here: https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#resource-types 
Do you think it would make sense to document this in our doc set?

**Comment by siamaksade** [comment]
@Preeticp @karthikjeeyar it definitely makes sense to expand the Tekton concepts and show examples there as well. Not just for resources and the types but also pipeline, tasks, etc.
